config/routes.rb
Rails.application.routes.draw do

	root 'contacts#index'
  resources :contacts

  get 'tags/:tag', to: 'contacts#index', as: :tag



  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:tag]
      @contacts = Contact.tagged_with(params[:tag])
    else
      @contacts = Contact.all.order('last_name ASC')
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone, :email, :address, :zip, :country, :avatar, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="pull-right">
  <%= link_to "index", contacts_path %>
</div>

<%= simple_form_for @contact do |f| %>

  <div class="input">
 
    <%= image_tag (contact.avatar.present? ? contact.avatar_url : "placeholder.jpg"), id: "avatar" %>

    <%= f.input :avatar, label: false, as: :file, :class => "btn btn-lg btn-default", id:'uploader_button' %>

    <div class="row">
      <hr>
      <div class="col-md-6">
        <%= f.input :first_name, label: "Prénom",required: false %>
      </div>
      <div class="col-md-6">
        <%= f.input :last_name, label: "Nom" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :address, label: "Adresse" %>
      </div>
      <div class="col-md-2">
        <%= f.input :zip, label: "CP" %>
      </div>
      <div class="col-md-4">
        <%= f.input :country, as: :string, label: "Pays" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :email %>
      </div>
      <div class="col-md-6">
        <%= f.input :phone, label: "Tél" %>
      </div>
    </div>
    <%= f.input :tag_list, label: "Tags", hint: "(séparés par des virgules)"%>
  </div>

  
  <%= f.button :submit, "Créer contact", :class => "btn btn-md btn-success " %>
  

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<div id='tag_cloud'>
  <% tag_cloud Contact.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class, id: 'tag' %>
  <% end %>
</div>

<hr>  
<div class="row">
  <% @contacts.each do |contact| %>
    <a href= "<%= contact_path(contact.id) %>">
      <div class="col-sm-6">
        <ul class="list-group">
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-12">
                
                  <%= image_tag (contact.avatar.present? ? contact.avatar_url(:thumb) : 'placeholder_min.jpg'), id: 'avatar' %>
                
                <h4><%= contact.last_name.upcase %> <%= contact.first_name.capitalize %></h4>
              </div>
            </div>
          </li>
        </ul>
      </div>  
    </a>       
  <% end %>
</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<div class="pull-right">
  <%= link_to 'Index', contacts_path %> |
  <%= link_to 'Editer', edit_contact_path(@contact) %> |
  <%= link_to 'Supprimer', contact_path(@contact), method: :delete, data: { confirm: 'Are you sure?' } %> 
</div>

<ul class="list-inline">
  <li>
    <%= image_tag (@contact.avatar.present? ? @contact.avatar_url : 'placeholder.jpg'), id: 'avatar' %>
  </li>
  <li>
    <h4><%= @contact.last_name.upcase %> <%= @contact.first_name.capitalize %></h4>
  </li>
</ul>

<hr>

<p>
  <strong>Adresse:</strong>
  <%= @contact.address.capitalize %>
</p>


<div class="row">
  <div class="col-xs-6">
    <strong>CP:</strong>
    <%= @contact.zip %>
  </div>
  <div class="col-xs-6">
    <strong>Pays:</strong>
    <%= @contact.country.upcase %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6">
    <strong>Email:</strong>
    <%= @contact.email %>
  </div>
  <div class="col-xs-6"> 
    <strong>Tél:</strong>
    <%= @contact.phone %>
  </div> 
</div>

<hr>


<b>Tags: <%= raw(@contact.tag_list.map { |t| link_to t, tag_path(t), id: 'tag' }.sort.join()) %></b>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <div>
        <%= link_to '+', new_contact_path, :class => "btn btn-sm btn-success pull-right", id: 'add_button'%>
        <h1><%= link_to "Contacts App", root_path %></h1>
      </div>
    </div>

    <hr>

    <div class="container" id="main">
      <div class="col-md-2"></div>
      <div class="col-md-8">
    		<%= yield %>
    	</div>
    </div>
  </body>
</html>